### ISSUE TITLE
Documentation on Usage

### ISSUE THREAD

**Issue by peterjungx** [edus44/vue-cli-plugin-yaml#1]
Hey, great work! I think this package is exactly what I need. 

it would be great to see a line or two how this supposed to work in the Vue app. I want to use a Yaml file in my Vue app.

**Comment by ycs77** [comment]
```js
import exampleYaml from './example.yml'

console.log(exampleYaml)
```

**Comment by edus44** [comment]
Added some usage info on Readme. Thanks
